# /home/ubuntu/saas-final-project/compose.yml
services:
  # Runs Prisma migrations once, then exits
  migrator:
    build:
      context: .
      target: build          # uses the "build" stage (has pnpm + Prisma)
    entrypoint: [""]
    working_dir: /app
    env_file: .env.production
    command: ["pnpm","exec","prisma","migrate","deploy"]
    restart: "no"

  # Next.js production server (standalone)
  web:
    build:
      context: .
      target: runner         # uses the "runner" final stage from your Dockerfile
    env_file: .env.production
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    ports:
      - "80:3000"            # visit http://YOUR_EC2_PUBLIC_IP
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
